Feature/wdboggs/timeformat iso8601
GEOS-ESM/MAPL pull request #1629
Opened 2022-08-08 18:50 UTC by darianboggs

## Description

Implementing ISO 8601 (Date/Time) support for MAPL
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

2022-08-08 19:21 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +#ifndef DEBUG
Please eliminate the `#ifndef DEBUG` prior to merge.

2022-08-08 19:22 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +      type(ISO8601Time) :: time_
Looks like you probably do not need the trailing underscores now, as your accessors all have `get_` ...

2022-08-08 19:30 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +                  istart = 0
There seems to be lots of problems here.  First, the entire conditional is very long and screams for helper procedures.

But it is also the case that `hours` is a saved variable and would seem to accidentally be positive the second time this procedure is called.    I at least cannot follow the logic.   

Also, istart is given a value at the end of this subblock, and then never referenced again ...

2022-08-08 19:31 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +!         duration%seconds_= seconds
Uncomment or delete.

2022-08-08 19:31 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +      _RETURN(_FAILURE)
```suggestion
      _FAIL('Not implemented')
      _RETURN(_SUCCESS)
```

2022-08-08 19:32 UTC, tclune commented on base/MAPL_ISO8601_Time.F90
> +!   end function get_digits
Uncomment or delete.

2022-08-08 19:33 UTC, tclune requested changes
See inline comments.

2022-08-08 21:09 UTC, tclune commented on shared/tests/test_MAPL_ISO8601_DateTime.pf
> +!      @assertEqual(-300, time%timezone_offset_)
Now the tests have comments that should either be deleted or uncommented ...

2022-08-08 21:11 UTC, tclune commented on shared/MAPL_ISO8601_DateTime.F90
>                    if(minutes < 0) minutes = 0
Still lots of references to uninitialized values scattered through this code.

2022-08-08 21:11 UTC, tclune submitted a review, later dismissed
See inline comments.

2022-08-09 20:48 UTC, darianboggs commented on base/MAPL_ISO8601_Time.F90
> +!         duration%seconds_= seconds
Fixed

2022-08-09 20:48 UTC, darianboggs commented on base/MAPL_ISO8601_Time.F90
> +      _RETURN(_FAILURE)
Replaced.

2022-08-09 20:49 UTC, darianboggs commented on base/MAPL_ISO8601_Time.F90
> +!   end function get_digits
Deleted

2022-09-29 17:18 UTC, darianboggs commented
Clean up for merge

2022-10-03 13:07 UTC, mathomp4 approved these changes

2022-10-03 13:29 UTC, merged