MAPL_GranuleGridFactory draft
GEOS-ESM/MAPL pull request #1987
Opened 2023-02-24 21:18 UTC by metdyn

## Description
 
GranuleGridFactory is an extension of the LatLonGridFactory where a logically rectangular grid from observation can be read from netCDF. HistoryGridComp can use GranuleGridFactory to output/interpolate fields from cube sphere to this rectilinear grid.
 
## Related Issue
 - A few initialization methods are not tested and need further work:
    -  initialize_from_file_metadata
    - initialize_from_esmf_distGrid
    -  GranuleGridFactory_from_parameters

 - I have not worked on the _RC macro replacement yet. 

 
## Motivation and Context
 - This work is useful for a general interpolation from model to obs grid
 
## How Has This Been Tested?

ExtDataDriver.x is used to test the code.  Thank @bena-nasa for many help!
A non-uniform quasi-rectangular grid as below can be imported to ESFM_grid and output to history. 

 lons =
  2.20069098472595, 23.1008815765381, 47.0075759887695, 68.9785690307617,
  1.8676301240921, 22.6600914001465, 46.9890670776367, 67.7191543579102,
  1.92321562767029, 22.9546718597412, 45.2667770385742, 67.6193466186523,
  1.21984219551086, 24.2904720306396, 46.9641456604004, 69.6375961303711,
  0.8646280169487, 23.2427845001221, 45.0278625488281, 67.8411560058594,
  1.97048604488373, 23.4698524475098, 45.4552268981934, 69.0879135131836 ;

 lats =
  -29.5109596252441, -29.8664703369141, -29.5538692474365, -29.6714305877686,
  -19.5849704742432, -19.9644241333008, -19.5579853057861, -19.9512977600098,
  -9.57261848449707, -9.89896202087402, -9.94071674346924, -9.97347927093506,
  0.271076053380966, 0.397882521152496, 0.436476975679398, 0.475021362304688,
  10.1921396255493, 10.1650629043579, 10.0061912536621, 10.0758123397827,
  20.4378852844238, 20.2155227661133, 20.1011619567871, 20.3528709411621 ;

 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
 
## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

2023-02-27 13:34 UTC, mathomp4 commented
@metdyn A couple of things to do (just so you can get used to it).

1. You need to make an entry in our `CHANGELOG.md` for this PR. We require it on all but the most trivial PRs (e.g., updated a readme). We follow [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) style which is pretty self-explanatory.
2. You need to add a label letting us know if this is 0-diff or non-zero-diff. What we mean by that is "If you run this PR with a C48 run of GEOSgcm, does it change the state?" Now, I can't see how this could, so "0 diff" is probably the right label.

2023-02-27 15:31 UTC, metdyn commented
@mathomp4, thank for explaining the details and it is very helpful!

2023-02-27 18:13 UTC, tclune requested changes
We also need to change this from "Granule" to "Swath".  My mistake in calling it the former - apologies for that.   Arlindo was insistent that it be Swath, so may as well correct it here (consistently).

2023-02-28 14:09 UTC, mathomp4 commented
Ooh. I see another issue. You are making this PR against `main`. As a new feature it should be against `develop`. Did you start from `main` or `develop` when you made this PR?

2023-02-28 17:37 UTC, metdyn commented
Thank you @mathomp4 for letting me know.  I had started from develop, but switched to main later on.  Now I need to make changes and merge to develop. I will rename this branch to Swath, close this PR and resubmit the PR to merge to develop.

2023-02-28 17:37 UTC, closed without merging

2023-02-28 17:59 UTC, bena-nasa commented
On first glance, I'm quite confused, why are there any 1D coordinate arrays being stored at all as part of the class definition? The whole point of this is that that we are going to read in coordinates that do not satisfy the criteria potentially of a lat-lon grid (the lon or lat if fixed as one of the grid indices vary). So I would think that the class itself storing any coordinates is unnecessary, the grid has hooks for the coordinates...

2023-02-28 18:32 UTC, bena-nasa commented
Also if we are supporting corner coordinates in this grid factory (which we should!)
The ESMF_GridCreate needs this added:

```
            gridEdgeLWidth=[0,0], &
            gridEdgeUWidth=[0,1], &
```

2023-02-28 18:32 UTC, metdyn commented on base/MAPL_GranuleGridFactory.F90
> +      real(kind=REAL64), allocatable :: lat_centers(:)
@bena-nasa  I think you are referring to this array, not used in the following code.  I see it is mainly used in  `subroutine initialize_from_file_metadata`, which is not used as initilization.  And this initialization array is
has a 1D dimension, which is the starting address in Fortran array.    It appears that in swath we need lon(nx, ny).  But I am not very sure.  But the bottom line is to make consistency as in `file_metadata` related procedures.

2023-02-28 18:33 UTC, metdyn commented on base/MAPL_GranuleGridFactory.F90
> +      real(kind=REAL64), allocatable :: lat_centers_degrees(:)
@bena-nasa  you are right, these variables are not used and I will remove it.

2023-02-28 18:46 UTC, metdyn commented
> So I would think that the class itself storing any coordinates is unnecessary, the grid has hooks for the coordinates...

The debate seems to be why we need to have `subroutine initialize_from_file_metadata` in swath code.  Currently in this swath code, the initialization from this code uses ` add_horz_coordinates_from_file`, we used allocatable arrays centers(nx,ny), then deallocated them after pass to the `ESMF_GridGetCoord` via ` farrayPtr=fptr`.    Then the ESMF data is passed to metadata.    Do we need to get metadata back to this SwathGridFacrtory, maybe for time dependence?  

BTW, I realized in the MAPL_TripolarGridFactory.F90, there is no array storage like `lat_centers(:)` in the class memebers. I copied the code from MAPL_LatLonGridFactory.F90, which is using this array.

2023-02-28 18:51 UTC, metdyn commented
@bena-nasa , after our discussion, I deleted `gridEdgeLWidth=[0,0], &  gridEdgeUWidth=[0,1], &`.  Right now, I think systematically we donot need corners, which removed a layer of complexity.

2023-03-01 14:28 UTC, bena-nasa commented
Another comment,
initialize_from_file_metadata method can easily be tested.

This can be done via ExtDataDriver.x, just take a test case, like case1 and substitute the grid definition in the AGCM1.rc and AGCM2.rc file **from being a lat-lon grid to this new grid factory at whatever resolution you want. That is all you should have to do, if that case1 doesn't work after swapping the grid definition, then the factory is broken** 

The first go-through of ExtDataDriver.x will create the files via History on the granule/swath factory. Then in 2nd go through, it will read these back in via ExtData which uses initialize_from_file_metadata when reading the input files.

2023-03-01 15:49 UTC, metdyn commented
@bena-nasa  This is a good suggestion and I will give it a try!