Fixed a bug that a file is being written by more than one processors simultaneously
GEOS-ESM/MAPL pull request #2230
Opened 2023-07-12 18:39 UTC by weiyuan-jiang

This PR is addressing issue #2228. When a file is written at different time step, it may lead to crash because different processes may try to write to it simultaneously. 
## Description

The captain process keep a record of the files being written. If a request to write a file which is still in the record, it wait for the completion of that process.
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ ] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

2023-07-12 18:40 UTC, weiyuan-jiang commented
@bena-nasa Could you please help to test my change?

2023-07-13 19:46 UTC, bena-nasa commented
> @bena-nasa Could you please help to test my change?

Yes, I will give this a workout

2023-07-17 19:04 UTC, mathomp4 commented
@weiyuan-jiang Note that when you are happy with this code, it probably should be re-done as a hotfix against `main` rather than a bugfix against `develop`. Since this is the sort of fix that might need to be backported to older tags, it's probably good to have it isolated from all the other work on develop.

Plus as @tclune would say, it's a bug on main in released code so it's a hotfix!

2023-07-18 15:49 UTC, tclune commented on .github/workflows/enforce-labels.yml
> +      - uses: mheap/github-action-required-labels@v5
Something is amiss. This file should not have been touched.  I fear you started with the wrong baseline.

2023-07-18 15:50 UTC, tclune commented
This PR started from an incorrect branch.   Need to start over from fresh copy off `main` branch.

2023-07-18 15:50 UTC, tclune requested changes
Start from `main` not `develop`

2023-07-18 15:53 UTC, closed without merging