Create submodule files in LatLon
GEOS-ESM/MAPL pull request #2899
Opened 2024-07-11 18:13 UTC by JulesKouatchou

## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [x] Ran the Unit Tests (`make tests`)

## Description
- Rename the folder `latlon` (in `geom_mgr) as `LatLon`.
- Create submodule files in `LatLon`.
- Change the version of `ESMA_cmake` from 3.46.0 to 3.37.0.

## Related Issue

2024-07-11 18:15 UTC, JulesKouatchou commented
Made a mistake in the ESMA_cmake version number. It should have been 3.47.0.

2024-07-11 18:20 UTC, tclune commented on geom_mgr/LatLon/CMakeLists.txt
> +          new_LatLonDecomposition_topo.F90 get_lon_distribution.F90
As I mentioned in Teams - the constructors should stay in the module and not be split as submodules.

2024-07-11 18:20 UTC, tclune commented on geom_mgr/LatLon/CMakeLists.txt
> +  SOURCES new_LatAxis.F90 equal_to.F90 not_equal_to.F90 supports_hconfig.F90
put constructors back in module

2024-07-11 18:21 UTC, tclune commented on geom_mgr/LatLon/CMakeLists.txt
> +          new_LonAxis.F90 supports_metadata.F90)
constructors go in module

2024-07-11 18:22 UTC, tclune requested changes
Constructors should stay in their original location.  Generally these are functions that start with the `new_` prefix.

Otherwise is fine.

2024-07-11 20:16 UTC, JulesKouatchou commented
Ok. I will make the changes right now. I will run tests before I push the changes.

2024-07-11 22:43 UTC, JulesKouatchou commented
Moved the constructors back to module files.

2024-07-12 12:36 UTC, tclune approved these changes

2024-07-12 13:42 UTC, mathomp4 commented
Hmm. Seems like a file is missing:

```
CMake Error at ESMA_cmake/esma_support/esma_add_*******_submodules.cmake:23 (target_sources):
  Cannot find source file:

    /root/project/workspace/build-MAPL/geom_mgr/LatLon/LatLonDecomposition_get_lon_distribution.F90
```

2024-07-12 13:44 UTC, tclune commented
It is on the main branch of ESMA_cmake (just checked).  Maybe we need a CI update in this PR?

2024-08-12 18:05 UTC, mathomp4 commented
> It is on the main branch of ESMA_cmake (just checked). Maybe we need a CI update in this PR?

It should work. I pressed the update branch button just now to see.

2024-08-22 16:34 UTC, JulesKouatchou commented
I will close this PR. I will make a few edits to the branch and submit a new PR.

2024-08-22 16:34 UTC, closed without merging