fixes #2996
GEOS-ESM/MAPL pull request #2998
Opened 2024-08-27 20:14 UTC by bena-nasa

Fixes #2996 

## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
- [ ] Refactor (no functional changes, no api changes)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [ ] Ran the Unit Tests (`make tests`)

## Description

## Related Issue

2024-08-27 20:49 UTC, tclune commented on generic3g/ESMF_HConfigUtilities.F90
> +
Am confused?   These are not used anywhere.

2024-08-27 20:51 UTC, tclune commented on generic3g/ESMF_HConfigUtilities/MAPL_HConfigMatch.F90
> +            b_as_bool  = ESMF_HConfigAsLogical(b, _RC)
Perhaps this would be clearer now using `SELECT CASE (a_tag)`?

2024-08-27 20:52 UTC, tclune submitted a review, later dismissed
Approving.  But see my comment about SELECT CASE.  If you concur, I can approve again after the change.

2024-08-28 13:19 UTC, tclune requested changes
The various `_RETURN_SUCCESS` statements are not required once you switch to SELECT CASE.   Sorry - should have hinted at that a bit more clearly.


Also, since there is now one more iteration ... please change the DEFAULT clause to check instead that it is a string tag.  Then the default clause should be a FAIL mesasge about an unsupported tag.   Future proofing us against an exotic tag from a clever end user.

2024-08-28 17:48 UTC, bena-nasa commented
> The various `_RETURN_SUCCESS` statements are not required once you switch to SELECT CASE. Sorry - should have hinted at that a bit more clearly.
> 
> Also, since there is now one more iteration ... please change the DEFAULT clause to check instead that it is a string tag. Then the default clause should be a FAIL mesasge about an unsupported tag. Future proofing us against an exotic tag from a clever end user.

changed

2024-08-28 18:27 UTC, tclune approved these changes

2024-08-28 18:43 UTC, merged