Adds a mpeu StrTemplate Replacement
GEOS-ESM/MAPL pull request #544
Opened 2020-09-16 16:53 UTC by WilliamJamieson

Adds a wrapper for `fill_grads_template` which allows MAPL to provide the same interface (name and arguments) as the `StrTemplate` from `GMAO_Shared/GMAO_mpeu` (see [`m_StrTemplate.F90`](https://github.com/GEOS-ESM/GMAO_Shared/blob/main/GMAO_mpeu/m_StrTemplate.F90)). 

## Description

Replicates all the functionality of the mpeu version except for true support of the `preserve` option.

## Related Issue

## Motivation and Context

GOCART2G should be independent of the `GMAO_Shared`, but it currently needs the mpeu provided `StrTemplate`. Since GOCART2G relies on MAPL, it makes sense to provide this functionality directly from MAPL.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [ ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

2020-09-16 17:08 UTC, atrayano approved these changes
Looks OK

2020-09-25 16:13 UTC, tclune requested changes
Since preserve is not supported,  stat should be set to failure if preserve is passed in (and has value  .true.)

2020-09-25 16:32 UTC, WilliamJamieson commented
Added requested change.

2020-09-25 18:28 UTC, tclune approved these changes

2020-09-25 20:48 UTC, merged