add stretch factor to output in History
GEOS-ESM/MAPL pull request #638
Opened 2020-12-11 21:56 UTC by bena-nasa

Fixes #634 

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [X] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

2020-12-11 22:33 UTC, tclune requested changes
Should we uptick the version as well?    This change is backward compatible, but maybe someone will want to key off version for writing a script someday or something.

2020-12-11 22:48 UTC, bena-nasa commented
Good point, I moved the version to 2.91, I wasn't sure what it should be 2.90.1 instead. I wasn't sure how we got 2.90, 3.0 seems to big, we didn't break any compatibility.

2020-12-14 12:53 UTC, tclune commented
We must have decided back then that `<major>.<minor>` was sufficient.  Not sure how we got all the way up to "90" though.

2020-12-14 12:54 UTC, tclune approved these changes

2020-12-14 12:54 UTC, merged